const products = [
  {
    id: 1,
    name: "Camiseta Titular 2022",
    price: 6500,
    img: "../src/img/camiseta-titular.jpg",
    category: "juego",
    stock: {
      xs: 10,
      s: 5,
      l: 20,
      xl: 15,
      xxl: 0,
      xxxl: 2,
    },
    spotlight: true,
  },
  {
    id: 2,
    name: "Camiseta Titular 2022",
    price: 6500,
    img: "../src/img/camiseta-titular.jpg",
    category: "juego",
    stock: {
      xs: 10,
      s: 5,
      l: 20,
      xl: 15,
      xxl: 0,
      xxxl: 2,
    },
    spotlight: true,
  },
  {
    id: 3,
    name: "Camiseta Titular 2022",
    price: 6500,
    img: "../src/img/camiseta-titular.jpg",
    category: "juego",
    stock: {
      xs: 10,
      s: 5,
      l: 20,
      xl: 15,
      xxl: 0,
      xxxl: 2,
    },
    spotlight: true,
  },
  {
    id: 4,
    name: "Camiseta Titular 2022",
    price: 6500,
    img: "../src/img/camiseta-titular.jpg",
    category: "juego",
    stock: {
      xs: 10,
      s: 5,
      l: 20,
      xl: 15,
      xxl: 0,
      xxxl: 2,
    },
    spotlight: true,
  },
  {
    id: 5,
    name: "Camiseta Titular 2022",
    price: 6500,
    img: "../src/img/camiseta-titular.jpg",
    category: "juego",
    stock: {
      xs: 10,
      s: 5,
      l: 20,
      xl: 15,
      xxl: 0,
      xxxl: 2,
    },
    spotlight: true,
  },
];

export { products };
